# Generated by Django 4.2 on 2024-04-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_menu_parrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='parrent',
            new_name='parent',
        ),
    ]
